name: landing
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  oyt_front_auth:
    path: ./packages/oyt_front_auth
  oyt_front_core:
    path: ./packages/oyt_front_core
  oyt_front_product:
    path: ./packages/oyt_front_product
  oyt_front_table:
    path: ./packages/oyt_front_table
  oyt_front_widgets:
    path: ./packages/oyt_front_widgets

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
